spring:
    application:
        name: profile-service
    datasource:
        url: jdbc:postgresql://localhost:5433/user-db
        driver-class-name: org.postgresql.Driver
        username: root
        password: password
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format-sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect 
    kafka:
        bootstrap-servers: 
            - localhost:9092
        topics:
            customer:
                create-profile: create-customer-profile-topic
                update-username: update-customer-username-topic
                update-email: update-customer-email-topic
                update-phone-number: update-customer-phone-number-topic
                delete-profile: delete-customer-profile-topic
            root:
                create-profile: create-root-profile-topic
                update-username: update-root-username-topic
                update-email: update-root-email-topic
                update-phone-number: update-root-phone-number-topic
                delete-profile: delete-root-profile-topic
            seller:
                create-profile: create-seller-profile-topic
                update-username: update-seller-username-topic
                update-email: update-seller-email-topic
                update-phone-number: update-seller-phone-number-topic
                delete-profile: delete-seller-profile-topic
server:
    port: 8081
