spring:
    application:
        name: profile-service
    datasource:
        url: jdbc:postgresql://localhost:5433/user-db
        driver-class-name: org.postgresql.Driver
        username: root
        password: password
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format-sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect 
    kafka:
        bootstrap-servers: 
            - localhost:9092
        topics:
            create-profile: create-profile-topic
            update-username: update-username-topic
            update-email: update-email-topic
            update-phone-number: update-phone-number-topic
            delete-profile: delete-profile-topic
server:
    port: 8081
